# Generated by Django 5.2 on 2025-05-28 13:44

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palletphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.inspection_photo_upload_path),
        ),
        migrations.AlterField(
            model_name='productloading',
            name='car_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер машины'),
        ),
        migrations.AlterField(
            model_name='productloading',
            name='mushroom_temperature',
            field=models.FloatField(blank=True, null=True, verbose_name='Температура гриба, °C'),
        ),
        migrations.AlterField(
            model_name='productloading',
            name='refrigerator_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Авторефрижератор'),
        ),
        migrations.AlterField(
            model_name='productloading',
            name='seal_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Пломба SGS'),
        ),
        migrations.AlterField(
            model_name='productloading',
            name='transport_temperature',
            field=models.FloatField(blank=True, null=True, verbose_name='Температура транспортировки, °C'),
        ),
        migrations.AlterField(
            model_name='productloadingphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.inspection_photo_upload_path),
        ),
    ]
